import random


def generate_mad_lib(adjective, noun, verb):
    """Return a short mad-lib style story that includes the three inputs.

    The returned string must contain the provided words (case preserved).
    """
    if adjective is None:
        adjective = ""
    if noun is None:
        noun = ""
    if verb is None:
        verb = ""

    story = (
        f"In a faraway land there lived a {adjective} {noun}. "
        f"Every morning the {noun} would {verb} with great enthusiasm, "
        f"and folks would smile at the {adjective} sight."
    )
    return story


def guessing_game():
    """Run a simple number guessing game (1-100) using input/print.

    Keeps prompting the user until they guess the number generated by
    `random.randint(1, 100)`. Provides feedback for too low / too high
    and a congratulatory message when correct.
    """
    target = random.randint(1, 100)
    print("I'm thinking of a number between 1 and 100. Try to guess it!")

    while True:
        user_input = input("Your guess: ")
        try:
            guess = int(user_input)
        except Exception:
            print("Please enter a valid integer.")
            continue

        if guess < target:
            print("Too low. Try again.")
        elif guess > target:
            print("Too high. Try again.")
        else:
            print("Congratulations! You guessed correctly.")
            break
